const SERVER_PORT = 3001

const TICK_RATE = 15
const TICK_LENGTH_MS = 1000 / TICK_RATE // -> 66ms -> 15 fps

const AREA = 20
const CANVAS_SIZE = 500
const CELL_SIZE = CANVAS_SIZE / AREA
const PLAYER_SIZE = CELL_SIZE

const PLAYER_NAME_MAX_LENGTH = 12

export { SERVER_PORT, TICK_LENGTH_MS, CANVAS_SIZE, CELL_SIZE, PLAYER_SIZE, PLAYER_NAME_MAX_LENGTH }
